version: "3.1"
services:
  web:
    image: odoo:15
    container_name: web-odoo
    depends_on:
      - db
    volumes:
      - odoo-web-data:/var/lib/odoo
      - ./config:/etc/odoo
      - ./local-addons:/mnt/extra-addons
    environment:
      - USER=odoo
      - PASSWORD=odoo
    networks:
      - odoo
  db:
    image: postgres:13
    container_name: db-odoo
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_PASSWORD=odoo
      - POSTGRES_USER=odoo
      - PGDATA=/var/lib/postgresql/data/pgdata
    volumes:
      - odoo-db-data:/var/lib/postgresql/data/pgdata
    ports:
      - "5455:5432"
    networks:
      - odoo
  proxy:
    container_name: proxy-odoo
    depends_on:
            - web
    build:
        context: .
        dockerfile: Dockerfile-nginx
    ports:
        - "8069:8069"
    networks:
      - odoo

networks:
  odoo:
    driver: bridge


volumes:
  odoo-web-data:
  odoo-db-data: